### PR TITLE
quote the `--data` argument for `tl_sizes()`

### LINKED ISSUE #329: `tl_sizes()` does not return sizes for installed LaTeX packages
I can reproduce the same behavior also at the terminal, so I am guessing that this is not strictly related to the R package, but then I am also not sure how to solve this issue and would appreciate any help :)

# Reprex with session info in R

``` r
options(error = traceback)
library(tinytex)

length(tl_pkgs())
#> [1] 277

tl_sizes()
#> tlmgr info --list --only-installed --data name,size
#> The total size is 0 bytes
#> [1] package size    size_h 
#> <0 rows> (or 0-length row.names)

xfun::session_info("tinytex")
#> R version 4.1.1 (2021-08-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19043)
#> 
#> Locale:
#>   LC_COLLATE=English_United Kingdom.1252 
#>   LC_CTYPE=English_United Kingdom.1252   
#>   LC_MONETARY=English_United Kingdom.1252
#>   LC_NUMERIC=C                           
#>   LC_TIME=English_United Kingdom.1252    
#> 
#> Package version:
#>   graphics_4.1.1  grDevices_4.1.1 stats_4.1.1     tinytex_0.33.1 
#>   tools_4.1.1     utils_4.1.1     xfun_0.26
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.1 (2021-08-10)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United Kingdom.1252 
#>  ctype    English_United Kingdom.1252 
#>  tz       Europe/Berlin               
#>  date     2021-09-14                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                        
#>  backports     1.2.1      2020-12-09 [1] CRAN (R 4.1.0)                
#>  cli           3.0.1      2021-07-17 [1] CRAN (R 4.1.0)                
#>  crayon        1.4.1      2021-02-08 [1] CRAN (R 4.1.1)                
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.1.1)                
#>  ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)                
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.1)                
#>  fansi         0.5.0      2021-05-25 [1] CRAN (R 4.1.1)                
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.1)                
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.1.1)                
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.1.1)                
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.1.1)                
#>  htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.1)                
#>  knitr         1.34       2021-09-09 [1] CRAN (R 4.1.1)                
#>  lifecycle     1.0.0      2021-02-15 [1] CRAN (R 4.1.1)                
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.1)                
#>  pillar        1.6.2      2021-07-29 [1] CRAN (R 4.1.1)                
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.1)                
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.1)                
#>  reprex        2.0.1      2021-08-05 [1] CRAN (R 4.1.1)                
#>  rlang         0.4.11     2021-04-30 [1] CRAN (R 4.1.1)                
#>  rmarkdown     2.10       2021-08-06 [1] CRAN (R 4.1.1)                
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.1)                
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.1.1)                
#>  stringi       1.7.4      2021-08-25 [1] CRAN (R 4.1.1)                
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.1)                
#>  styler        1.5.1.9001 2021-09-13 [1] Github (r-lib/styler@6300c7c) 
#>  tibble        3.1.4      2021-08-25 [1] CRAN (R 4.1.1)                
#>  tinytex     * 0.33.1     2021-09-14 [1] Github (yihui/tinytex@0aaac57)
#>  utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.1)                
#>  vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.1.1)                
#>  withr         2.4.2      2021-04-18 [1] CRAN (R 4.1.1)                
#>  xfun          0.26       2021-09-14 [1] CRAN (R 4.1.1)                
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)                
#> 
#> [1] C:/Users/IndrajeetPatil/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-4.1.1/library
```

</details>

# Output from terminal

```bash
PS C:\Users\IndrajeetPatil> tlmgr info --list --only-installed --data name,size
tlmgr.pl: package size not locally!
tlmgr.pl: action info returned an error; continuing.
tlmgr.pl: An error has occurred. See above messages. Exiting.
```

### PR DESCRIPTION
**Pull request by cderv**
Fix #329

With this PR, `tl_sizes()` works on WINDOWS

````
> tl_sizes(pkgs = "luatex")
tlmgr info --list --only-installed --data "name,size" luatex
The total size is 148 Kb
  package   size size_h
1  luatex 151552 148 Kb
````

@IndrajeetPatil can you test the PR also ? 

@yihui I added a test ~but not sure they run on Windows anyway. 🤷~ Forget that, We already switched to GHA so it works

### CODE REVIEW

**Review by yihui — APPROVED** [review]
Thanks!

File: tests/test-travis/test-tlmgr.R [hunk 1]
```diff
@@ -17,6 +17,12 @@ assert('`tlmgr info` can list the installed packages', {
   (c('xetex', 'luatex', 'graphics') %in% res)
 })
 
+assert('`tl_size()` can correctly list name and size', {
+  res = tl_sizes(pkgs = "luatex")$package
+  # only check a few basic packages
+  ('luatex' %==% tl_sizes(pkgs = "luatex")$package)
```
Comment (IndrajeetPatil) [inline tests/test-travis/test-tlmgr.R:23]: @cderv Out of curiosity, where is the `%==%` operator from?

GitHub search was not very useful.

Comment (cderv) [reply tests/test-travis/test-tlmgr.R:23]: It is from **testit** framework that we are using for testing in this package
https://github.com/yihui/testit
